/*
 * wycheproof_test.c — run Wycheproof-style HMAC-SHA256 edge-case vectors against the REAL
 * in-tree Sha2.c (ROI-TOP-50 item 36).
 *
 * The vectors (WP_VECS) are generated by wycheproof_vectors.py, whose expected tags come from
 * Python's own hmac/hashlib (the independent oracle). This harness recomputes each tag with an
 * HMAC-SHA256 built on the real compiled sha256 (object #2), and:
 *   - VALID vector   -> recomputed tag must EQUAL the expected tag (byte-for-byte);
 *   - INVALID vector -> recomputed 32-byte tag must NOT equal the supplied (tampered/truncated)
 *                       tag, i.e. a verifier correctly REJECTS it.
 *
 * Negative control (-DWP_NEGCTL): a deliberately broken HMAC that does NOT hash keys longer
 * than the block (it truncates them instead). It must FAIL at least one edge vector — the
 * key=65 / key=128 cases — proving those boundary vectors actually catch a real bug. A build
 * that passes every vector with the break in place would mean the edge coverage is vacuous.
 */
#include <stdio.h>
#include <string.h>
#include "Crypto/Sha2.h"
#include "wycheproof_vectors.h"

#define BLK 64
#define DIG 32

/* HMAC-SHA256 over the real in-tree sha256. When WP_NEGCTL is defined, the key-normalisation
 * step is broken on purpose (over-long keys are truncated, not hashed) to serve as the control. */
static void hmac_sha256 (const unsigned char *k, int kl, const unsigned char *m, int ml,
                         unsigned char out[DIG])
{
	sha256_ctx c; unsigned char k0[BLK], pad[BLK], in[DIG]; int i;
	if (kl > BLK) {
#if defined(WP_NEGCTL)
		memcpy (k0, k, BLK);                       /* BROKEN: truncate an over-long key */
#else
		sha256_begin (&c); sha256_hash ((unsigned char *)k, (unsigned) kl, &c);
		sha256_end (k0, &c); memset (k0 + DIG, 0, BLK - DIG);   /* correct: hash then zero-pad */
#endif
	} else {
		if (kl > 0) memcpy (k0, k, (size_t) kl);
		memset (k0 + (kl > 0 ? kl : 0), 0, BLK - (kl > 0 ? kl : 0));
	}
	for (i = 0; i < BLK; i++) pad[i] = k0[i] ^ 0x36;
	sha256_begin (&c); sha256_hash (pad, BLK, &c);
	if (ml > 0) sha256_hash ((unsigned char *)m, (unsigned) ml, &c);
	sha256_end (in, &c);
	for (i = 0; i < BLK; i++) pad[i] = k0[i] ^ 0x5c;
	sha256_begin (&c); sha256_hash (pad, BLK, &c); sha256_hash (in, DIG, &c); sha256_end (out, &c);
}

int main (void)
{
	int i, valid_ok = 0, invalid_ok = 0, fails = 0;
	unsigned char got[DIG];
	for (i = 0; i < WP_NVEC; i++) {
		const WpVec *v = &WP_VECS[i];
		hmac_sha256 (v->key, v->keyLen, v->msg, v->msgLen, got);
		if (v->valid) {
			/* correct implementation reproduces the Python-oracle tag exactly */
			if (v->tagLen == DIG && memcmp (got, v->tag, DIG) == 0) valid_ok++;
			else { fails++; printf ("  tc%d VALID mismatch (key=%d msg=%d)\n", v->tcId, v->keyLen, v->msgLen); }
		} else {
			/* tampered/truncated tag must NOT match the honest recompute -> rejected */
			if (!(v->tagLen == DIG && memcmp (got, v->tag, DIG) == 0)) invalid_ok++;
			else { fails++; printf ("  tc%d INVALID accepted (should reject)\n", v->tcId); }
		}
	}
	printf ("  vectors=%d  valid_matched=%d  invalid_rejected=%d  fails=%d\n",
	        WP_NVEC, valid_ok, invalid_ok, fails);
#if defined(WP_NEGCTL)
	/* The control MUST have broken at least one boundary vector. */
	if (fails > 0) { printf ("NEGCTL-OK: broken HMAC fails %d edge vector(s) as required\n", fails); return 0; }
	printf ("NEGCTL-FAIL: broken HMAC passed every vector — edge coverage is vacuous\n"); return 1;
#else
	if (fails == 0) { printf ("PASS: real Sha2.c HMAC-SHA256 matches the Wycheproof-style edge vectors\n"); return 0; }
	printf ("FAIL: %d vector(s) mismatched\n", fails); return 1;
#endif
}
