#!/usr/bin/env python3
"""wycheproof_vectors.py — Wycheproof-style edge-case vector generator for HMAC-SHA256
(ROI-TOP-50 item 36).

HMAC-SHA256 is load-bearing across the fork (salt-binding, duress-token recognition, the
keyslot area MAC, the per-share Shamir MAC), so it is the primitive most worth hammering with
adversarial edge cases rather than one happy-path KAT. In the spirit of Google's Wycheproof
project, this targets the boundaries where naive HMAC implementations break:

  - key length exactly 0, 1, digest size (32), block size (64), block+1 (65), and 2*block (128)
    — the 64/65 boundary is where a correct HMAC must start HASHING the key; a buggy one that
    truncates instead produces a WRONG tag there (that is the negative control below);
  - message length 0, 1, and around the SHA-256 block/padding boundaries (55/56/63/64/65/127);
  - degenerate key/message bytes (all-zero, all-0xff);
  - INVALID cases: a correct tag with one bit flipped, and a truncated tag — both must be
    REJECTED by a verifier that recomputes and compares.

The expected tag for every VALID case is computed with Python's own hmac/hashlib — the
independent reference implementation (oracle #1). The C harness recomputes each tag with the
real in-tree Sha2.c (object #2); agreement between the two is the two-way proof.

Usage:
  python3 wycheproof_vectors.py --emit-header   # write a C header of {key,msg,tag,result}
  python3 wycheproof_vectors.py                 # human-readable listing (count + a few rows)
"""
import sys, hmac, hashlib

def mac(key: bytes, msg: bytes) -> bytes:
    return hmac.new(key, msg, hashlib.sha256).digest()

def build():
    """Return a list of (tcId, comment, key, msg, tag, result) with result in {valid,invalid}."""
    key_lens = [0, 1, 16, 32, 64, 65, 128]
    msg_lens = [0, 1, 55, 56, 63, 64, 65, 127]
    vecs = []
    tc = 1
    # cross of representative key/msg edge sizes, incrementing byte patterns
    for kl in key_lens:
        for ml in msg_lens:
            key = bytes((i * 7 + 1) & 0xff for i in range(kl))
            msg = bytes((i * 3 + 2) & 0xff for i in range(ml))
            vecs.append((tc, f"key={kl} msg={ml}", key, msg, mac(key, msg), "valid")); tc += 1
    # degenerate byte patterns at the critical 64/65 key boundary
    for kl in (64, 65):
        for pat, name in ((0x00, "zero"), (0xff, "ff")):
            key = bytes([pat]) * kl
            msg = b"boundary"
            vecs.append((tc, f"key={kl}/{name} msg=8", key, msg, mac(key, msg), "valid")); tc += 1
    # INVALID: flip one bit of a correct tag  -> must be rejected
    k = bytes(range(32)); m = b"flip-one-bit"
    good = mac(k, m); bad = bytearray(good); bad[-1] ^= 0x01
    vecs.append((tc, "tag last-bit flipped", k, m, bytes(bad), "invalid")); tc += 1
    # INVALID: truncated tag (16 of 32 bytes) -> length mismatch, must be rejected
    vecs.append((tc, "tag truncated to 16", k, m, good[:16], "invalid")); tc += 1
    return vecs

def emit_header(vecs):
    def carr(b):
        return "{" + ",".join(str(x) for x in b) + "}" if b else "{0}"
    out = []
    out.append("/* GENERATED by wycheproof_vectors.py — do not edit. HMAC-SHA256 edge vectors. */")
    out.append("#ifndef WYCHEPROOF_VECTORS_H\n#define WYCHEPROOF_VECTORS_H")
    out.append("typedef struct { int tcId; int keyLen, msgLen, tagLen; int valid;")
    out.append("  unsigned char key[128], msg[160], tag[32]; } WpVec;")
    out.append(f"#define WP_NVEC {len(vecs)}")
    out.append("static const WpVec WP_VECS[WP_NVEC] = {")
    for tc, cmt, key, msg, tag, res in vecs:
        out.append(f"  {{{tc},{len(key)},{len(msg)},{len(tag)},{1 if res=='valid' else 0},"
                   f"{carr(key)},{carr(msg)},{carr(tag)}}}, /* {cmt} {res} */")
    out.append("};\n#endif")
    return "\n".join(out)

def main():
    vecs = build()
    if "--emit-header" in sys.argv:
        sys.stdout.write(emit_header(vecs) + "\n"); return
    nvalid = sum(1 for v in vecs if v[5] == "valid")
    ninval = len(vecs) - nvalid
    print(f"wycheproof-style HMAC-SHA256: {len(vecs)} vectors ({nvalid} valid, {ninval} invalid)")
    for tc, cmt, key, msg, tag, res in vecs[:3]:
        print(f"  tc{tc} [{res}] {cmt}: tag={tag.hex()[:32]}...")

if __name__ == "__main__":
    main()
